<a href="https://colab.research.google.com/github/devdezzies/deep-learning-with-pytorch/blob/main/00_dl_with_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

video: https://www.youtube.com/watch?v=V_xro1bcAuA&t=4795s

resources:

In [1]:
import torch

print(torch.__version__)

2.3.1+cu121


In [ ]:
!nvidia-smi

Thu Jul 25 14:43:08 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Intro to Tensors

docs - https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html

In [2]:
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [9]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [14]:
MATRIX[1]

tensor(10)

In [15]:
TENSOR = torch.tensor([[[1, 2, 3], [2, 3, 4], [7, 3, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [2, 3, 4],
         [7, 3, 9]]])

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

###  Random tensors

Why random tensors?
You set a random numbers -> look at data -> update random numbers -> look at data -> update random numbers ...

We start from random tensors full of random numbers adn then adjust those numbers to better represent the data.

In [21]:
### create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
print(type(random_tensor))
print(random_tensor)

<class 'torch.Tensor'>
tensor([[0.7446, 0.1876, 0.1230, 0.6827],
        [0.3312, 0.5239, 0.9740, 0.3869],
        [0.7550, 0.6417, 0.9821, 0.1309]])


In [18]:
random_tensor.ndim

2

In [19]:
random_tensor.shape

torch.Size([3, 4])

In [28]:
random_image_size_tensor = torch.rand(size=(244, 244, 3)) # height, width, colour channel (RGB)
random_image_size_tensor.ndim, random_image_size_tensor.shape

## whether you use size= or not (it will give similar result)

(3, torch.Size([244, 244, 3]))

In [29]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
ones = torch.ones(size=(3, 4), dtype=torch.float64)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [36]:
ones.dtype
## the default dtype is float32

torch.float64

### range of tensors and tensors-like

In [38]:
# use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
one_to_twenty = torch.arange(start=1, end=21, step=1)
one_to_twenty

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])

In [44]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor datatypes
3 big errors you'll run into with PyTorch and DL:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [53]:
float_64_tensor = torch.tensor([[3.0, 6.0, 9.0], [1.0, 2.0, 3.3]],
                               dtype=torch.float64,
                               device=None,
                               requires_grad=False)
float_64_tensor.dtype

torch.float64

In [54]:
float_16_tensor = float_64_tensor.type(torch.HalfTensor)
float_16_tensor.dtype

torch.float16