## Introduction to Tensors

In [2]:
import torch 

print("PyTorch version: ", torch.__version__)
print("CUDA available: ", torch.cuda.is_available())
print("CUDA device count: ", torch.cuda.device_count())
print("CUDA device name: ", torch.cuda.get_device_name(0))

PyTorch version:  2.4.0
CUDA available:  True
CUDA device count:  1
CUDA device name:  NVIDIA GeForce GTX 1650


In [145]:
def get_tensor_information(ts: torch.tensor):
    print(f'tensor size: {ts.shape}')
    print(f'tensor device: {ts.device}')

In [146]:
tensor = torch.rand(size=(244, 244, 3), dtype=torch.float32, device='cuda')
tensor

tensor([[[0.5904, 0.6163, 0.2682],
         [0.9415, 0.9526, 0.4654],
         [0.5286, 0.4651, 0.0111],
         ...,
         [0.2726, 0.9292, 0.0063],
         [0.8688, 0.8713, 0.1433],
         [0.9343, 0.1997, 0.4044]],

        [[0.6491, 0.1013, 0.3360],
         [0.3177, 0.6092, 0.1338],
         [0.1465, 0.8783, 0.7093],
         ...,
         [0.1090, 0.9328, 0.4559],
         [0.1245, 0.6122, 0.3091],
         [0.4827, 0.4753, 0.8246]],

        [[0.3454, 0.1510, 0.2287],
         [0.0080, 0.0090, 0.0589],
         [0.6208, 0.9899, 0.7778],
         ...,
         [0.6733, 0.6867, 0.7278],
         [0.3530, 0.2606, 0.2246],
         [0.0130, 0.2943, 0.2947]],

        ...,

        [[0.4067, 0.4521, 0.0997],
         [0.2042, 0.3346, 0.4879],
         [0.1846, 0.6161, 0.9020],
         ...,
         [0.4859, 0.4467, 0.4521],
         [0.4847, 0.4499, 0.7140],
         [0.2897, 0.5344, 0.2330]],

        [[0.5929, 0.5906, 0.9139],
         [0.5211, 0.8002, 0.7054],
         [0.

In [147]:
get_tensor_information(ts=tensor)

tensor size: torch.Size([244, 244, 3])
tensor device: cuda:0


In [148]:
int_32_tensor = torch.tensor(dtype=torch.int32, data=[1,2,3])
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [149]:
int_32_tensor.ndim

1

In [150]:
int_32_tensor.shape

torch.Size([3])

In [151]:
random_tensor = torch.rand(size=(5,5))
random_tensor

tensor([[0.4616, 0.1931, 0.9081, 0.7012, 0.4511],
        [0.2540, 0.6338, 0.3720, 0.3937, 0.4158],
        [0.3141, 0.0032, 0.6912, 0.3702, 0.0270],
        [0.2201, 0.1360, 0.3317, 0.5385, 0.5064],
        [0.3563, 0.8837, 0.6803, 0.5643, 0.8072]])

In [152]:
torch.matmul(random_tensor, random_tensor)

tensor([[0.8624, 0.7084, 1.6582, 1.3680, 1.0322],
        [0.6299, 0.8729, 1.1371, 1.0121, 0.9232],
        [0.4540, 0.1391, 0.9054, 0.6920, 0.3709],
        [0.5393, 0.6505, 1.0029, 0.9064, 0.8462],
        [1.0145, 1.4211, 1.8590, 1.6091, 1.4839]])

In [153]:
torch.matmul(random_tensor, random_tensor)

tensor([[0.8624, 0.7084, 1.6582, 1.3680, 1.0322],
        [0.6299, 0.8729, 1.1371, 1.0121, 0.9232],
        [0.4540, 0.1391, 0.9054, 0.6920, 0.3709],
        [0.5393, 0.6505, 1.0029, 0.9064, 0.8462],
        [1.0145, 1.4211, 1.8590, 1.6091, 1.4839]])

In [154]:
a_tensor = torch.tensor(data=[1,2,3])
a_tensor

tensor([1, 2, 3])

In [155]:
a_tensor.shape

torch.Size([3])

### Manipulating Tensors

Tensor operations include: 
- addition
- substraction
- multiplication (element-wise)
- division
- matrix multiplication

In [157]:
#create a tensor
ts = torch.tensor([1, 2, 3])
ts

tensor([1, 2, 3])

In [158]:
ts = ts * 10
ts

tensor([10, 20, 30])

In [159]:
# using pytorch in-built functions
torch.mul(ts, 10)

tensor([100, 200, 300])

### Matrix multiplication

There are two main ways to perform matrix multiplication:
1. element-wise
2. dot-product

There are two main rules that peforming matrix multiplication needs to satisfy: 
1. the **inner dimensions** must match:
   - `(3, 2) @ (3, 2)` won't work
   - `(3, 2) @ (2, 3)` will work
2. the resulting matrix has the shape of the **outer dimension**:
   - `(2, 3) @ (3, 2)` -> `(2,2)`
  
playground - http://matrixmultiplication.xyz/

In [161]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.6669, 1.1584, 0.7954],
        [0.3683, 1.1317, 0.9053],
        [0.1107, 0.2540, 0.1905]])

In [162]:
%%time
torch.matmul(a_tensor, a_tensor)
## For 2D tensors (matrices): torch.matmul(A, B) performs matrix multiplication.
## For 1D tensors (vectors): torch.matmul(a, b) performs the dot product if one of the tensors is 1D and the other is 2D or if both are 1D.

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### one of the most common errors in deep learning: shape errors

In [164]:
# shapes for matrix multiplication
tensor_a = torch.tensor([[1,2],
                         [3,2],
                         [4,3]])
tensor_b = torch.tensor([[2,3],
                         [4,3],
                         [6,7]])
## these tensors cannot be multiplied because the inner dimensions aren't the same
## we need to perform matrix transpose

In [165]:
tensor_a.shape, tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

In [167]:
print(f"Original size of matrix a = {tensor_a.shape} and matrix b = {tensor_b.shape}")
print(f"They cannot be multiplied since their inner dimensions don't match")
print(f"\nWe can perform a matrix manipulation to one of the matrices")
print(f"Transposed matrix b: {tensor_b.T}")
print("matrix b.T still contains the same information as the original matrix b")
print(f"\nNow these matrices have the same inner dimension a = {tensor_a.shape}; b = {tensor_b.T.shape}")

Original size of matrix a = torch.Size([3, 2]) and matrix b = torch.Size([3, 2])
They cannot be multiplied since their inner dimensions don't match

We can perform a matrix manipulation to one of the matrices
Transposed matrix b: tensor([[2, 4, 6],
        [3, 3, 7]])
matrix b.T still contains the same information as the original matrix b

Now these matrices have the same inner dimension a = torch.Size([3, 2]); b = torch.Size([2, 3])


In [168]:
multiplied_matrices = torch.matmul(tensor_a, tensor_b.T)
multiplied_matrices

tensor([[ 8, 10, 20],
        [12, 18, 32],
        [17, 25, 45]])

### 3D tensors multiplication
For tensors A with shape (B, M, N) and B with shape (B, N, P), where B is the batch size:
The last dimension of A (size N) must match the second-to-last dimension of B (also size N).
The resulting tensor will have shape (B, M, P).

In [170]:
three_dimension_ts1 = torch.rand(size=(5, 2, 7))
three_dimension_ts1

tensor([[[0.9792, 0.5916, 0.6480, 0.2012, 0.4116, 0.5660, 0.1653],
         [0.8036, 0.2433, 0.8742, 0.4764, 0.0940, 0.5091, 0.2099]],

        [[0.6341, 0.1848, 0.2307, 0.2465, 0.9886, 0.8422, 0.1126],
         [0.8342, 0.6953, 0.6705, 0.6000, 0.2178, 0.8318, 0.4849]],

        [[0.8131, 0.9017, 0.5346, 0.1460, 0.9409, 0.0096, 0.2617],
         [0.0436, 0.6678, 0.6411, 0.2986, 0.0234, 0.9415, 0.9009]],

        [[0.3647, 0.6253, 0.1005, 0.3377, 0.3207, 0.7800, 0.2217],
         [0.6796, 0.7060, 0.1853, 0.8315, 0.3965, 0.4804, 0.0223]],

        [[0.1771, 0.2697, 0.6300, 0.8726, 0.8202, 0.5205, 0.5117],
         [0.5762, 0.1266, 0.0970, 0.6497, 0.6526, 0.8365, 0.4009]]])

In [171]:
three_dimension_ts2 = torch.rand(size=(5,7,1))
three_dimension_ts2

tensor([[[0.3007],
         [0.2591],
         [0.9153],
         [0.6505],
         [0.2475],
         [0.9388],
         [0.0623]],

        [[0.0678],
         [0.1897],
         [0.3446],
         [0.9484],
         [0.1479],
         [0.8436],
         [0.3454]],

        [[0.7430],
         [0.1851],
         [0.7432],
         [0.9532],
         [0.6149],
         [0.6040],
         [0.2260]],

        [[0.1321],
         [0.7898],
         [0.8037],
         [0.7510],
         [0.0717],
         [0.2487],
         [0.4965]],

        [[0.4696],
         [0.6931],
         [0.6916],
         [0.2630],
         [0.9885],
         [0.1822],
         [0.2685]]])

In [172]:
torch.matmul(three_dimension_ts1, three_dimension_ts2)

tensor([[[1.8152],
         [1.9290]],

        [[1.2869],
         [1.8900]],

        [[1.9510],
         [1.7037]],

        [[1.2035],
         [1.5797]],

        [[1.9783],
         [1.5015]]])

### Tensors Aggregation
Finding the min, max, mean, sum, etc (tensor aggregation)

In [174]:
# create a 1d tensor 
x = torch.arange(start=0, end=100, step=10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [175]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [176]:
# find the max
## torch.max(x), x.max() 
## will give an error since its dtype is int

In [177]:
x.dtype

torch.int64

In [178]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [179]:
three_dim_tensor = torch.rand(3,4,5)
three_dim_tensor

tensor([[[0.3228, 0.8969, 0.9265, 0.5376, 0.4329],
         [0.0527, 0.2495, 0.4521, 0.0107, 0.5801],
         [0.1347, 0.2516, 0.8805, 0.2787, 0.0993],
         [0.2075, 0.0159, 0.3399, 0.9333, 0.7788]],

        [[0.8409, 0.4047, 0.7687, 0.8850, 0.3130],
         [0.8999, 0.7674, 0.4619, 0.6300, 0.4086],
         [0.5013, 0.5331, 0.3427, 0.7516, 0.1924],
         [0.0819, 0.8963, 0.9758, 0.2010, 0.0741]],

        [[0.6645, 0.5485, 0.9966, 0.3861, 0.7572],
         [0.9555, 0.4507, 0.2430, 0.1926, 0.5652],
         [0.2393, 0.0394, 0.5275, 0.9876, 0.1265],
         [0.3006, 0.2623, 0.8119, 0.1858, 0.8745]]])

In [180]:
torch.min(three_dim_tensor)

tensor(0.0107)

## Finding the positional min and max

In [182]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [183]:
x.argmin(), x.argmax(), x[0], x[9]

(tensor(0), tensor(9), tensor(0), tensor(90))

## Reshaping, viewing, and stacking tensors - 2.57

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor (viewing a tensor from a different perspective)
* Stacking - combine multiple tensors on top of each other
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimension permuted (swapped) in a certain way

In [185]:
# create a tensor  
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [186]:
x_reshape = x.reshape(1, 9)
x_reshape, x_reshape.shape, x_reshape.ndim
## now the tensor become a 2d tensor

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [187]:
x_reshape = x.reshape(9,1)
x_reshape, x_reshape.shape, x_reshape.ndim

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 2)

In [188]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [189]:
x_reshape = x.reshape(2, 5) #hint: 5 * 2 = 10
x_reshape, x_reshape.shape, x_reshape.ndim

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]),
 2)

In [190]:
# change the view
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [191]:
# changing z changes x (because a view of a tensor shares the same memory, as the original tensor
z[0, 9] = 1 # it's like z[0][9]
z, x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9., 1.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1.]))

In [192]:
z = x.view(2, 5) # 2 rows and 5 columns
z[:, 1] = 0 # means that I want to set all numbers in column 1 to 0 no matter its rows
z

tensor([[1., 0., 3., 4., 5.],
        [6., 0., 8., 9., 1.]])

In [193]:
z[:, 3] = 9
z, x # the information will be the same, but in z we see it in a different view

(tensor([[1., 0., 3., 9., 5.],
         [6., 0., 8., 9., 1.]]),
 tensor([1., 0., 3., 9., 5., 6., 0., 8., 9., 1.]))

In [194]:
# stack tensor on top of each other (vstack dim=0)
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 0., 3., 9., 5., 6., 0., 8., 9., 1.],
        [1., 0., 3., 9., 5., 6., 0., 8., 9., 1.],
        [1., 0., 3., 9., 5., 6., 0., 8., 9., 1.],
        [1., 0., 3., 9., 5., 6., 0., 8., 9., 1.]])

In [195]:
# squeezing - removes all the single dimension size 1
x_reshape = x.reshape(1, 10)
x_reshape, x_reshape.shape, x_reshape.squeeze() ## it changes the tensor to 1 dimension - x_reshape.size = [1, 10] so it removes all the one dimension

(tensor([[1., 0., 3., 9., 5., 6., 0., 8., 9., 1.]]),
 torch.Size([1, 10]),
 tensor([1., 0., 3., 9., 5., 6., 0., 8., 9., 1.]))

In [196]:
x_reshape.squeeze().shape

torch.Size([10])

In [197]:
# torch.squeeze(input, dim=None) - removes all single dimension from a target tensor
print(f'Previous tensor: {x_reshape}')
print(f'Previous shape: {x_reshape.shape}')

# Remove extra dimension from x_reshape
x_squeezed = x_reshape.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shape: {x_squeezed.shape}')

Previous tensor: tensor([[1., 0., 3., 9., 5., 6., 0., 8., 9., 1.]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([1., 0., 3., 9., 5., 6., 0., 8., 9., 1.])
New shape: torch.Size([10])


In [198]:
# torch.unsqueeze(input, dim) - add a single dimension to a target tensor at a specific dim (dimension)
print(f'Previous target tensor: {x_squeezed}')
print(f'Previous target shape: {x_squeezed.shape}')

# Add an extra dimenstion with unsqueeze at a dimension 0
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew target tensor: {x_unsqueezed}')
print(f'New target shape: {x_unsqueezed.shape}')

# Add an extra dimenstion with unsqueeze at a dimension 1
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f'\nNew target tensor: {x_unsqueezed}')
print(f'New target shape: {x_unsqueezed.shape}')

Previous target tensor: tensor([1., 0., 3., 9., 5., 6., 0., 8., 9., 1.])
Previous target shape: torch.Size([10])

New target tensor: tensor([[1., 0., 3., 9., 5., 6., 0., 8., 9., 1.]])
New target shape: torch.Size([1, 10])

New target tensor: tensor([[1.],
        [0.],
        [3.],
        [9.],
        [5.],
        [6.],
        [0.],
        [8.],
        [9.],
        [1.]])
New target shape: torch.Size([10, 1])


In [199]:
# torch.permute(input, dims) - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(244, 244, 3)) # [height, width, color_channels(rgb)]

# permute the original tensor to  rearrange the axis (or dim) order 
x_permuted = x_original.permute(2, 0, 1) # [color_channels, height, width] 

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}')

Previous shape: torch.Size([244, 244, 3])
New shape: torch.Size([3, 244, 244])


In [200]:
# torch.permute Returns a view of the original tensor input with its dimensions permuted.
## it changes the original tensor when changing the permuted tensor 

x_original[0, 0, 0]

tensor(0.2736)

In [201]:
x_permuted[0,0,0] = 2.
x_original[0,0,0], x_permuted[0,0,0]

(tensor(2.), tensor(2.))

## Indexing (selecting data from tensors)

In [203]:
 # create a tensor with 3 dimensions
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [204]:
# index on the first dimension (dim=0)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [205]:
# index on the second dimension (dim=1)
x[0][0]

tensor([1, 2, 3])

In [206]:
# indec on the third dimension (dim=2)
x[0][0][0]

tensor(1)

In [207]:
# you can use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [208]:
# Get all values 1st and 2nd dimension but only index 1 of 3rd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [209]:
# Get all values of the 1st dimension (dim=0) but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [210]:
# Get index 0 of 1st dimension and 2nd dimension and all values of 3rd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [211]:
# index on x to return 9 
x[0,2,2]

tensor(9)

In [212]:
# index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

In [213]:
x = torch.arange(1., 11.)
x, x.is_contiguous(), x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 True,
 torch.Size([10]))

In [214]:
x = x.squeeze()
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [215]:
y = x.reshape(2,5).T
y, y.is_contiguous()

(tensor([[ 1.,  6.],
         [ 2.,  7.],
         [ 3.,  8.],
         [ 4.,  9.],
         [ 5., 10.]]),
 False)

In [216]:
z = y.reshape(1,10)
z, z.is_contiguous()

(tensor([[ 1.,  6.,  2.,  7.,  3.,  8.,  4.,  9.,  5., 10.]]), True)

In [217]:
z[0, :] = 10
z, y # if a contiguous tensor was derived from a non-contigous tensor then they will be independent to each other

(tensor([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]]),
 tensor([[ 1.,  6.],
         [ 2.,  7.],
         [ 3.,  8.],
         [ 4.,  9.],
         [ 5., 10.]]))

In [298]:
x = torch.arange(1., 10.).reshape(1, 3, 3)
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [302]:
# Get all value of 0th and 1st dimensions but only index 1 of 2nd dimension 
x[:,:, 1]

tensor([[2., 5., 8.]])

In [310]:
# get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5.])

In [318]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :]

tensor([1., 2., 3.])

In [330]:
x[:, :, 2] ## give you the "all" values of index 0 (list)

tensor([[3., 6., 9.]])

In [334]:
x[0, :, 2] ## give you the first element of 0th dimension (element)

tensor([3., 6., 9.])

## PyTorch Tensors and NumPy

NumPy is a popular scientific Python numerical computing library
- NumPy -> PyTorch tensor `torch.from_numpy(ndarray)`
- PyTorch tensor -> NumPy `torch.Tensor.numpy()`

In [343]:
import numpy as np 

array = np.arange(1., 10.)
array, array.dtype

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]), dtype('float64'))

In [347]:
tensor = torch.from_numpy(array) ## the datatype of default value from numpy will be refelected by the tensor
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [359]:
tensor = torch.ones(10)
numpy_tensor = tensor.numpy() ## it also reflects the default dtype
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [365]:
# change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor ## tensor are not contagious (they don't share memory)

(tensor([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random) 

"The concept of neural network harnessing the power of randomness"

How a neural network learns: 
`start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again..`

To reduce the randomness in neural networks and PyTorch comes the concept of a `random seed.` Essentially what the seed does is "flavour" the randomness.

This is helpful because the program always give random numbers everytime it runs, so one of the case is that when you want to share the program to others (they will get random starter) this why the seed comes.

In [368]:
# create two random tensors 
random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4) 

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.7052, 0.5657, 0.1827, 0.0887],
        [0.9972, 0.7674, 0.1623, 0.5901],
        [0.0349, 0.9170, 0.7977, 0.1646]])
tensor([[0.2411, 0.7798, 0.3834, 0.7981],
        [0.7011, 0.2700, 0.0622, 0.6193],
        [0.5112, 0.9024, 0.7580, 0.7580]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [378]:
# Let's make some random but reproducible tensors using seed 
RANDOM_SEED = 0 # this can be absolutely arbitrary

torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4) 

torch.manual_seed(RANDOM_SEED) ## this procedure is only for one tensor assignment
random_tensor_d = torch.rand(3, 4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Different ways of accessing a GPU and making faster computations

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA + PyTorch

### 1. Getting a GPU

1. use google colab
2. use your own GPU
3. use cloud computing - GCP, AWS, Azure

### 2. Check for GPU access with PyTorch
For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code

learn more - https://pytorch.org/docs/stable/notes/cuda.html

In [401]:
# check for GPU access with PyTorch
torch.cuda.is_available()

True

In [412]:
# setup device agnostic code 
device = "cuda" if torch.cuda.is_available() else "cpu"

In [416]:
# count number of devices
torch.cuda.device_count()

1

### 3. Setting up device agnostic code and putting tensors on and off the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [441]:
# create a tensor (default on the CPU)
tensor = torch.rand(3, 4)

tensor, tensor.device

(tensor([[0.5139, 0.4569, 0.6012, 0.8179],
         [0.9736, 0.8175, 0.9747, 0.4638],
         [0.0508, 0.2630, 0.8405, 0.4968]]),
 device(type='cpu'))

In [461]:
tensor_on_gpu = tensor.to(device) ## to move the tensor into a specific processing unit
tensor_on_gpu, tensor_on_gpu.device

(tensor([[0.5139, 0.4569, 0.6012, 0.8179],
         [0.9736, 0.8175, 0.9747, 0.4638],
         [0.0508, 0.2630, 0.8405, 0.4968]], device='cuda:0'),
 device(type='cuda', index=0))

### 4. Moving tensors back to the CPU

In [451]:
# if tensor is on GPU, can't tranform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [463]:
# to fix the GPU tensor with NumPy issue, we can set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([[0.5138961 , 0.45686555, 0.6011907 , 0.81791973],
       [0.9736231 , 0.81752795, 0.97470677, 0.46383917],
       [0.05083925, 0.2629614 , 0.8404526 , 0.49675876]], dtype=float32)